source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZBadgeView_Example', :exclusive => true do
  pod 'DZBadgeView', :path => '../'
end

target 'DZBadgeView_Tests', :exclusive => true do
  pod 'DZBadgeView', :path => '../'

  pod 'FBSnapshotTestCase'
end
